### ISSUE TITLE
Alpha

### ISSUE THREAD

**Issue by MartinLoriente** [mnavjeev/asker_ps1#1]
The code doesnt return the results for alpha and beta. In your results png you show a code "final2" that shows the results for BLP but that doesnt exist in the main python coding.

**Comment by FranInduni** [comment]
The code doesnt return the results for alpha and beta. In your results png you show a code "final2" that shows the results for BLP but that doesnt exist in the main python coding.

**Comment by mnavjeev** [comment]
Code returns delta values. You should be able recover alpha and beta from projecting these onto product characteristics
